### ISSUE TITLE
Homebrew formula missing

### ISSUE THREAD

**Issue by Vinz87** [csete/gpredict#112]
I installed Homebrew to install gpredict 2.0 on OS X 10.11, as suggested in the home page, but the formula "brew install gpredict" doesn't work.
Was it removed for the new 2.0 update? Has it changed?

**Comment by Vinz87** [comment]
Homebrew says what follows:
_gpredict was deleted from homebrew/core in commit ee7405d:
  Migrate some formula with hard-X11 dependencies.
  We have the homebrew-x11 tap for this reason so let's migrate everything
  without any reverse dependencies. Ideally I'd also like to migrate
  everything that's :recommended and the GTK formulae through there too
  (or to a dedicated homebrew-gtk)._

I tried googling it but I didn't find an answer: what's homebrew-x11? a different version of homebrew?

**Comment by csete** [comment]
Sorry, but I have no idea. This is a bug tracker for gpredict, not homebrew. I have never had anything Mac OS X packaging related in gpredict repository, so you have to ask in the homebrew project.

**Comment by csete** [comment]
I checked the project and can see what you mean now. They have [deleted gpredict](https://github.com/Homebrew/homebrew-x11/commit/10f6880be9cfd012669066f7e99e7bd076b71ebd) because they didn't want to keep the old version of goocanvas. I don't recall getting any notice from them when they did that, but its OK. I will just remove the reference from the home page.

You can still get [gpredict 2.0 from Macports](https://www.macports.org/ports.php?by=name&substr=gpredict). It may be old fashioned, but at least it is reliable.

**Comment by Vinz87** [comment]
thank you
