### ISSUE TITLE
Autotrack

### ISSUE THREAD

**Issue by SQ5KTM** [csete/gpredict#176]
Hi, could someone explain the Autotrack mode?
Thank, You.

Michal
SQ5KTM

**Comment by csete** [comment]
Hi @SQ5KTM 

Sorry for the late reply... I missed this item since this is an issue tracker used for development, not a support forum, please see http://gpredict.oz9aec.net/User_Support.php

Autotrack is used for automatically tracking satellites as they come above the horizon. When a satellite in a module comes above the horizon, the radio and rotator controller will start tracking it. I hope this helped.

**Comment by SQ5KTM** [comment]
Thank You!

pt., 30 sie 2019 o 21:10 Alexandru Csete <notifications@github.com>
napisał(a):
