### ISSUE TITLE
Centre frequency in .trsp files

### ISSUE THREAD

**Issue by rutja76** [csete/gpredict#203]
Two issues about .trsp files, both related to the high difficulty in manually changing the transponder parameters.

1. Why .trsp files require entering transponder up_low, up_high, down_low, down_high frequencies? Wouldn't be much easier of entering directly the up and down centre frequencies? Those are anyway the frequencies shown in the radio window. If you want to fine adjust them by yourself, you always have to calculate the extremes from the desired frequencies. Not straightforward and very time consuming. In the code they are anyway transformed in the centre frequency before being used like in gtk-rig-ctrl.c:

```
        freq = ctrl->trsp->downlow +
            abs(ctrl->trsp->downhigh - ctrl->trsp->downlow) / 2;
```

Wouldn't be much easier to define just two variables, e.g. upfreq and downfreq and just work with them? Or maybe I just don't understand the idea behind it.

2. Since .trsp file is nowhere related to the name of the satellite, could its name be put at least in the file, e.g. SAT_NAME=AO-7? That would save time if you want to edit them. Now you have to open each satellite in gpredict, check for the satellite info, write down the catalogue number, go to the .trsp directory, look for that file and edit it. If the name of the sat were in a string inside the file, you could easily do a file search.

**Comment by csete** [comment]
1. Sorry you are having such a hard time editing the trsp files. You are probably not going to be happier when I tell you that your local changes will be lost the next time you run "Update transponder data". Transponder data is fetched from the [SatNOGS database](https://db.satnogs.org/) which is where changes should be made. There might come a merge functionality and an editor in gpredict in the future, although it is not on the current roadmap.

2. The satellite name can not be used as the unique identifier for an object because an object can have different names in different databases and even one name can refer to one or more objects each with their own catalog number.
