### ISSUE TITLE
[Question] Day/night terminator

### ISSUE THREAD

**Issue by chri87d9** [csete/gpredict#212]
Was searching for a day/night terminator feature, but was not sure if it was implemented yet. I was unable to find any info in the user manual, and could not find any settings regarding such a feature.

the reason i thought such a feature might be available was the thread: #37 , #3 .

**Comment by csete** [comment]
As you can see in issue #3 the feature is not yet complete. I have now updated the text to make it clear that it is not enabled in the user interface.

In the future, please add your relevant comments to the existing issue instead of opening a new one. Also note that technical support and discussions should take place on the technical support forums: http://gpredict.oz9aec.net/User_Support.php
