### ISSUE TITLE
Solar Terminator Other Features Not Working

### ISSUE THREAD

**Issue by GilbertGn** [csete/gpredict#262]
In regards to gpredict 2.2.2 or 2.3.33

1 - How do you get the Solar Terminator and Global shadow to display on the map view?
When I go to Preferences --> Map View
There is a list of items where the color can be changed. Included in the list is Solar Terminator and Global shadow. When I set either one to something like red and the opacity set to the maximum they don’t appear on the map view.

2 - The opacity/transparency slider appears not to work.

**Comment by LongnoseRob** [comment]
The soalr terminator works, as can be seen, please note that this is gpredict built from the latest master of this repo

![gpredict1](https://user-images.githubusercontent.com/17066917/119151204-21305180-ba8a-11eb-9a84-0080012461e2.png)
![gpredict2](https://user-images.githubusercontent.com/17066917/119151212-22617e80-ba8a-11eb-8b13-673a800770f1.png)

**Comment by GilbertGn** [comment]
Now that is interesting. 
I have two different versions running in two different environments.
- On Fedora 33 I have Gpredict version 2.2.2 
- RPi 3B running the latest release of Buster the Gpredict version is 2.3-33

But when I look at the Map View settings the check box for the Solar Terminator is missing.

The question why is it missing on both of the instances of Gpredict I have?

What OS is yours running on?

![F33](https://user-images.githubusercontent.com/84523963/119208472-4ca64280-ba70-11eb-9a72-afadb19e6cdb.png)
![Pi](https://user-images.githubusercontent.com/84523963/119208477-5039c980-ba70-11eb-944b-2407627839a6.png)
![F33-Options](https://user-images.githubusercontent.com/84523963/119208489-5c258b80-ba70-11eb-862b-2941f004e65a.png)

**Comment by LongnoseRob** [comment]
The screenshots were made on my PC with ArchLinux, gpredict compiled Freon the latest git sources.
Also have it running on ArchLinuxARM also bukt from the latest git sources.

**Comment by GilbertGn** [comment]
Could point me to the source you compiled from?
I got the gpredict-2.2.1.tar.bz2 from Github and that Solar Terminator check box is missing in the source. So I'm not sure what source you used.

**Comment by LongnoseRob** [comment]
there are two ways to get the lastest master of grpedict and compile it:
**1st way**
1. open a console and go to a directory where you would like to have the sources e.g. ~/builds
2. enter `git clone `https://github.com/csete/gpredict.git`
3. cd gpredict
4. enter `./autogen.sh`
5. enter `make` or 'make -j 4` (if you have a rather modern machine with more then 2GB of RAM)
6. enter `sudo make install`

**2nd way**

go to https://github.com/csete/gpredict
and cllick on the green code button and select zip-download
![github](https://user-images.githubusercontent.com/17066917/119218933-b4669700-bb1d-11eb-996f-0115bf892d06.png)
after downloaing the zip-file, unpack it to a folder of your choice and follow steps 4-6 from above.

PS I do not know which distribution you are using, and I did not include any steps to check if all requirements for compiling are installed.
If autogen.sh fails this is very probably due to missing packages required to compile or run gpredict/
Please also check the readme and the documentaton folder.

**Comment by GilbertGn** [comment]
Well I had some success. I was able to get to build on the F33 system and the "Solar Terminator" option is there and works.

But on the Raspberry Pi with OS release buster   **./autogen.sh** gives this error.....  **./autogen.sh: intltoolize: not found**

I can't find the package it belongs to. 
Do you have any idea what the package might be?

**Comment by LongnoseRob** [comment]
@GilbertGn great, glad that you got it compiled.
